spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: givepasswordhere
    driverClassName: org.postgresql.Driver
    initialization-mode: always
  jpa:
    generte-ddl : false
    hibernate:
      ddl-auto: none
    show_sql: true
    database-platform : org.hibernate.dialect.PostgreSQLDialect